### ISSUE TITLE
Question on implementation of the weighted soft-margin triplet loss

### ISSUE THREAD

**Issue by GrumpyZhou** [shiyujiao/cross_view_localization_SAFA#2]
Hi @shiyujiao ,

Thanks for the great project and making it open source.
I just got a small question about your code for the loss implementation.
Based on your codes referenced below:

https://github.com/shiyujiao/cross_view_localization_SAFA/blob/99584cbfa6fc0b7bf92bb2b3e05936e23ae6bc33/script/train_cvusa.py#L70-L72

It seems to me, you are calculating for also triplets made by two identical positive pairs. 
They should in theory be excluded right?

**Comment by shiyujiao** [comment]
Hi Grumpy,

Thanks for this question.

The variable "pos_dist" contains distance of all positive pairs, and the variable "dist_array" contains the distances between positive pairs and negtive pairs. 

For negative pairs, "pos_dist - dist_array" will construct the real triplets. 
For positive pairs, the results of "pos_dist - dist_array" will be zero. Thus "two identical positive pairs" are excluded.

Hope my explanation clear your question.

Yujiao

**Comment by shiyujiao** [comment]
> Hi @shiyujiao ,
> 
> Thanks for the great project and making it open source.
> I just got a small question about your code for the loss implementation.
> Based on your codes referenced below:
> 
> https://github.com/shiyujiao/cross_view_localization_SAFA/blob/99584cbfa6fc0b7bf92bb2b3e05936e23ae6bc33/script/train_cvusa.py#L70-L72
> 
> It seems to me, you are calculating for also triplets made by two identical positive pairs.
> They should in theory be excluded right?

Hi Grumpy,

Thanks for this question.

The variable "pos_dist" contains distance of all positive pairs, and the variable "dist_array" contains the distances between positive pairs and negtive pairs.

For negative pairs, "pos_dist - dist_array" will construct the real triplets.
For positive pairs, the results of "pos_dist - dist_array" will be zero. Thus "two identical positive pairs" are excluded.

Hope my explanation clear your question.

Yujiao

**Comment by GrumpyZhou** [comment]
Hi @shiyujiao ，

I know the (pos - dist_array) leads to 0 distance for the postive pairs, but they will still take effect in the loss. Since the loss of 0 distance is not zero and the goal of loss is to make the distance between positive pair and negative pair as big as possible, no?  And in your case, you are considering a positive pair to be a negative one, which is not correct, right?

So i assume it is better to directly exclude those positive-positive triplets by either manually setting diagnoal in loss_g2s to zero or pick only the off-diagonals for summation and mean.
How do you think?

**Comment by shiyujiao** [comment]
> Hi @shiyujiao ，
> 
> I know the (pos - dist_array) leads to 0 distance for the postive pairs, but they will still take effect in the loss. Since the loss of 0 distance is not zero and the goal of loss is to make the distance between positive pair and negative pair as big as possible, no? And in your case, you are considering a positive pair to be a negative one, which is not correct, right?
> 
> So i assume it is better to directly exclude those positive-positive triplets by either manually setting diagnoal in loss_g2s to zero or pick only the off-diagonals for summation and mean.
> How do you think?

Hi @GrumpyZhou ,

Sorry for this late reply. 

Your suggestion is good.

But I think it will not influence. For example, we want to optimize a function f = w1*(x1-x2) + w2*(x2 - x2). I think the second item will make no difference in the gradient of w1 and w2?

**Comment by GrumpyZhou** [comment]
Hi @shiyujiao,

Yes, i think you are right.  In theory, there is no difference.
